service: oriter-backend

plugins:
  - serverless-bundle

custom:
  bundle:
    sourcemaps: true
    caching: true
    stats: false
    linting: false
    packager: 'npm'
    targets:
      - node

provider:
  name: aws
  runtime: nodejs14.x
  role: arn:aws:iam::204684095875:role/ServerlessFrameworkIAMRole

functions:
  handleFormSubmission:
    handler: src/handlers/index.handler