AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application.
Resources:
  OriterFormSubmission:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
        Register:
          Type: Api
          Properties:
            Path: /register
            Method: post
        Submit:
          Type: Api
          Properties:
            Path: /submit
            Method: post
        VerifyFormLink:
          Type: Api
          Properties:
            Path: /verifyFormLink
            Method: post
        VerifyToken:
          Type: Api
          Properties:
            Path: /verifyToken
            Method: post
